name: Deploy PHP App via CLI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create deployment ZIP
      run: |
        powershell Compress-Archive -Path * -DestinationPath app.zip

    - name: Zip Deploy using Azure CLI
      run: |
        az webapp deploy --resource-group third --name webapp-php-sql --src-path app.zip --type zip
